apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

namespace: taskapp

patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
    target:
      kind: Deployment
      name: taskapp-frontend
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
    target:
      kind: Deployment
      name: taskapp-backend

images:
  - name: your-ecr-repo/taskapp-frontend
    newTag: "1.0.0"
  - name: your-ecr-repo/taskapp-backend
    newTag: "1.0.0"
