apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: taskapp
data:
  FLASK_ENV: "production"
  CORS_ORIGINS: "https://taskapp.durotoluwa-tasked.com"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: taskapp
data:
  REACT_APP_API_URL: "https://api.durotoluwa-tasked.com"
